# ============================================================
# ATHENA LABS — CASO-008
# Configuración exclusiva para monitoreo del repositorio
# ============================================================

database_in=file:/var/lib/aide/athena-labs.db
database_out=file:/var/lib/aide/athena-labs.db.new
database_new=file:/var/lib/aide/athena-labs.db.new
gzip_dbout=no

AthenaIntegrity = p+u+g+s+m+c+sha256+acl+xattrs+ftype

!/home/rodrigo/Documentos/Athena-Cybersecurity-Labs/Caso-008-Monitoreo-Integridad-AIDE/evidencias

/home/rodrigo/Documentos/Athena-Cybersecurity-Labs AthenaIntegrity
